import pandas as pd

from src.ingestion import load_all_data
from src.cleaning import clean_all_data
from src.validation import validate_all_data
from src.transformation import transform_all_data

from src.load_to_mysql import (
    load_valid_data_to_mysql,
    load_incremental_data_to_mysql
)

from src.quality.quality_engine import (
    run_data_quality_engine
)

from src.quality_report import (
    create_quality_report
)

from src.incremental_etl import (
    load_etl_state,
    save_etl_state,
    get_incremental_records
)


def run_pipeline():

    print("\n" + "=" * 70)
    print("HEALTHCARE DATA ENGINEERING PIPELINE")
    print("=" * 70)

    # =========================================================
    # STEP 1: INGESTION
    # =========================================================

    print("\n[1/8] INGESTION")

    data = load_all_data()

    for name, df in data.items():
        print(f"{name}: {len(df)} records")

    # =========================================================
    # STEP 2: CLEANING
    # =========================================================

    print("\n[2/8] CLEANING")

    cleaned_data = clean_all_data(data)

    for name, df in cleaned_data.items():
        print(f"{name}: {len(df)} cleaned records")

    # =========================================================
    # STEP 3: VALIDATION
    # =========================================================

    print("\n[3/8] VALIDATION")

    valid_data = validate_all_data(cleaned_data)

    print("\nValid records:")

    for name, df in valid_data.items():
        print(f"{name}: {len(df)}")

    # Read invalid records generated by validation.py
    invalid_data = {}

    print("\nInvalid records:")

    for name in valid_data:

        invalid_file = f"output/invalid_{name}.csv"

        try:

            invalid_df = pd.read_csv(
                invalid_file
            )

            invalid_data[name] = invalid_df

            print(
                f"{name}: {len(invalid_df)}"
            )

        except FileNotFoundError:

            invalid_data[name] = pd.DataFrame()

            print(
                f"{name}: 0"
            )

    # =========================================================
    # STEP 4: DATA QUALITY ENGINE
    # =========================================================

    print("\n[4/8] DATA QUALITY ENGINE")

    quality_rules_report = run_data_quality_engine(
        cleaned_data
    )

    quality_rules_report.to_csv(
        "output/data_quality_rules_report.csv",
        index=False
    )

    print(
        "Saved: output/data_quality_rules_report.csv"
    )

    # =========================================================
    # STEP 5: TRANSFORMATION
    # =========================================================

    print("\n[5/8] TRANSFORMATION")

    transformed_data = transform_all_data(
        valid_data
    )

    print("Transformations completed.")

    # =========================================================
    # STEP 6: QUALITY REPORT
    # =========================================================

    print("\n[6/8] QUALITY REPORT")

    create_quality_report(
        cleaned_data,
        valid_data,
        invalid_data
    )

    print(
        "Quality report generated."
    )

    # =========================================================
    # STEP 7: MYSQL LOAD
    # =========================================================

    print("\n[7/8] MYSQL LOAD")

    # Load previous ETL state
    state = load_etl_state()

    appointments_state = state[
        "appointments"
    ][
        "last_processed_date"
    ]

    billing_state = state[
        "billing"
    ][
        "last_processed_date"
    ]

    print("\nCurrent ETL state:")

    print(
        f"Appointments watermark: "
        f"{appointments_state}"
    )

    print(
        f"Billing watermark: "
        f"{billing_state}"
    )

    # =========================================================
    # FIRST RUN -> FULL LOAD
    # =========================================================

    if (
        appointments_state is None
        and billing_state is None
    ):

        print(
            "\nNo previous successful ETL run found."
        )

        print(
            "Running FULL LOAD..."
        )

        # Full load
        load_valid_data_to_mysql(
            valid_data
        )

        # Find latest successful appointment date
        appointment_dates = pd.to_datetime(
            valid_data[
                "appointments"
            ][
                "appointment_date"
            ],
            errors="coerce"
        )

        # Find latest successful billing date
        billing_dates = pd.to_datetime(
            valid_data[
                "billing"
            ][
                "transaction_date"
            ],
            errors="coerce"
        )

        latest_appointment_date = (
            appointment_dates
            .max()
            .strftime("%Y-%m-%d")
        )

        latest_billing_date = (
            billing_dates
            .max()
            .strftime("%Y-%m-%d")
        )

        # Update state ONLY after successful load
        save_etl_state(
            latest_appointment_date,
            latest_billing_date
        )

        print(
            "\nETL state updated "
            "after successful FULL LOAD."
        )

    # =========================================================
    # SUBSEQUENT RUN -> INCREMENTAL LOAD
    # =========================================================

    else:

        print(
            "\nPrevious ETL state found."
        )

        # -----------------------------------------------------
        # Incremental appointments
        # -----------------------------------------------------

        incremental_appointments = (
            get_incremental_records(
                valid_data[
                    "appointments"
                ],
                "appointment_date",
                appointments_state
            )
        )

        # -----------------------------------------------------
        # Incremental billing
        # -----------------------------------------------------

        incremental_billing = (
            get_incremental_records(
                valid_data[
                    "billing"
                ],
                "transaction_date",
                billing_state
            )
        )

        # -----------------------------------------------------
        # Services belonging to new appointments
        # -----------------------------------------------------

        new_appointment_ids = set(
            incremental_appointments[
                "appointment_id"
            ]
        )

        incremental_services = (
            valid_data[
                "appointment_services"
            ][
                valid_data[
                    "appointment_services"
                ][
                    "appointment_id"
                ].isin(
                    new_appointment_ids
                )
            ].copy()
        )

        # -----------------------------------------------------
        # Print incremental counts
        # -----------------------------------------------------

        print(
            f"\nIncremental appointments: "
            f"{len(incremental_appointments)}"
        )

        print(
            f"Incremental services: "
            f"{len(incremental_services)}"
        )

        print(
            f"Incremental billing: "
            f"{len(incremental_billing)}"
        )

        # -----------------------------------------------------
        # Load incremental records
        # -----------------------------------------------------

        if (
            not incremental_appointments.empty
            or not incremental_services.empty
            or not incremental_billing.empty
        ):

            load_incremental_data_to_mysql(
                appointments=incremental_appointments,
                appointment_services=incremental_services,
                billing=incremental_billing
            )

            # -------------------------------------------------
            # Calculate new appointment watermark
            # -------------------------------------------------

            if not incremental_appointments.empty:

                latest_appointment_date = (
                    pd.to_datetime(
                        incremental_appointments[
                            "appointment_date"
                        ]
                    )
                    .max()
                    .strftime("%Y-%m-%d")
                )

            else:

                latest_appointment_date = (
                    appointments_state
                )

            # -------------------------------------------------
            # Calculate new billing watermark
            # -------------------------------------------------

            if not incremental_billing.empty:

                latest_billing_date = (
                    pd.to_datetime(
                        incremental_billing[
                            "transaction_date"
                        ]
                    )
                    .max()
                    .strftime("%Y-%m-%d")
                )

            else:

                latest_billing_date = (
                    billing_state
                )

            # -------------------------------------------------
            # Update state ONLY after successful load
            # -------------------------------------------------

            save_etl_state(
                latest_appointment_date,
                latest_billing_date
            )

            print(
                "\nETL state updated successfully."
            )

        else:

            print(
                "\nNo new incremental records found."
            )

    # =========================================================
    # STEP 8: FINAL SUMMARY
    # =========================================================

    print("\n[8/8] FINAL SUMMARY")

    print(
        "\nHealthcare Data Engineering Pipeline "
        "completed successfully."
    )

    print("=" * 70)


# =============================================================
# MAIN
# =============================================================

if __name__ == "__main__":
    run_pipeline()